spring:
  application:
    name: config-server
  cloud:
    config:
      lable: master
      sever:
        git:
          uri: https://github.com/how2j/springcloudConfig/
            serchPaths: repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/